version: "3"
services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
      target: core-php
    volumes:
      - ./prestashop:/var/www/html/prestashop/prestashop
      - ./wordpress:/var/www/html/wordpress/wordpress
      - ./drupal:/var/www/html/drupal/drupal
  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: abc123.
      MYSQL_DATABASE: presta
      MYSQL_USER: prestauser
      MYSQL_PASSWORD: prestapw
    volumes:
      - ./db/data:/var/lib/mysql
      - ./db:/docker-entrypoint-initd.d
  nginx:
    image: nginx:alpine
    ports:
      - 80:80
      - 443:443
    links:
      - php
    volumes:
      - ./prestashop:/var/www/html/prestashop/prestashop
      - ./wordpress:/var/www/html/wordpress/wordpress
      - ./drupal:/var/www/html/drupal/drupal
      - ./cert:/etc/letsencrypt
      - ./nginx:/etc/nginx/conf.d 
      - ./symfony:/var/www/html/symfony

  symfony:
    build:
      context: .
      dockerfile: Dockerfile
      target: sv-symfony
    volumes:
      - ./symfony:/var/www/html/symfony
      - ./dev/.env:/var/www/html/symfony/.env

volumes:
  basedatos: