<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerY16NTKp\appAppKernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerY16NTKp/appAppKernelProdContainer.php') {
    touch(__DIR__.'/ContainerY16NTKp.legacy');

    return;
}

if (!\class_exists(appAppKernelProdContainer::class, false)) {
    \class_alias(\ContainerY16NTKp\appAppKernelProdContainer::class, appAppKernelProdContainer::class, false);
}

return new \ContainerY16NTKp\appAppKernelProdContainer([
    'container.build_hash' => 'Y16NTKp',
    'container.build_id' => 'ef6d9209',
    'container.build_time' => 1678384137,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerY16NTKp');
